baseURL = 'https://amarpandey.me/'
languageCode = 'en-us'
title = 'Amar Prakash Pandey - ᕦ(ò_óˇ)ᕤ'
theme = 'hugo-bearblog'
author = "Amar Prakash Pandey"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  Description = "Personal website of Amar Prakash Pandey. Currently working as a Solutions Consultant at Sahaj Software. I have also worked for Tata Research Design and Development Center, Tata Consultancy Service, and Google Summer of Code. Open Source Community Member at DuckDuckGo. Maintainer at Open Source Help Community."
  hideMadeWithLine = true
  favicon = "favicon/favicon.png"

[params.analytics]
  measurement_id = "G-CN34V0ZGSQ"
